### Numpy

These are two of the commonly used packages: Numpy is numerical python.

Numpy is array (or matrix) based and performs operations very quickly (very less time taken for huge calculations as compared to calculations on lists or base python computations for the same kind of operations). It can handle mathematics (MATLAB alternative), Plotting (matplotlib library), images, and very useful for performing heavy calculations using machine learning).

In [1]:
#Numpy and Pandas come with Anaconda but in case you need to install it use '!' to access terminal inside the notebook 
#Uncomment the commands below to install the packages (if not already installed) - it might take some time to install 
# !pip install numpy
# !pip install pandas

In [2]:
#Import the modules as a short name - commonly used as np and pd for numpy and panads 
import numpy as np 
import pandas as pd

In [3]:
#Simple array 1x2 and 2x2

a1 = np.array([1,2])

a = np.array([[1,2],[3,4]])
print(f'{a1} \n \n {a}')

[1 2] 
 
 [[1 2]
 [3 4]]


In [4]:
#shape (2x2), size (number of elements) Dimention (2d/3d etc. )
print(a.shape)
print(a.size)
print(a.ndim)

(2, 2)
4
2


In [5]:
d = np.array([[1,2,3],[1,3,2],[5,6,7]], ndmin = 3)
d # try for yourself n dimention arrays

array([[[1, 2, 3],
        [1, 3, 2],
        [5, 6, 7]]])

In [6]:
# Arange
# rank 1 ndarray that has sequential integers from 0 to 9
# x = [0 1 2 3 4 5 6 7 8 9]
x = np.arange(10)
print(x)
# rank 1 ndarray that has sequential integers from 4 to 9
# [start, stop)
# x = [4 5 6 7 8 9]
y = np.arange(4,10)
print(y)
# rank 1 ndarray that has evenly spaced integers from 1 to 13 in steps of 3.
# np.arange(start,stop,step)
# x = [ 1 4 7 10 13]
z = np.arange(1,14,3)
print(z)

[0 1 2 3 4 5 6 7 8 9]
[4 5 6 7 8 9]
[ 1  4  7 10 13]


In [7]:
s = np.array([1,2], dtype = 'int32') #try int32 to int16
s.itemsize #Shows the number of bytes of memory used
#s.size * s.itemsize, a.nbytes #Also a way to check the memory 

4

In [8]:
s = np.array(['yes', 'no'])

In [9]:
s.dtype #<U3 is Unicode string type

dtype('<U3')

In [10]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(a)

print('\n')

#Accessing specific elements in the array a[row,column]
#Note that both indexing starts at 0
#To access 9 which is in 1st row and 2nd column:
a[1,2] 

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]




9

In [11]:
#4 dimention array -- observe the number of square brackets
d = np.array([[1,2,3],[4,5,6],[7,8,9]], ndmin = 4)
d

array([[[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]])

In [12]:
type(d[0,0,1,2])

numpy.int64

In [13]:
d[0,0,1,-2]  #Negative indexing from the bottom/right

5

In [14]:
# Arange
# rank 1 ndarray that has sequential integers from 0 to 9
x = np.arange(10)
print(x)
# rank 1 ndarray that has sequential integers from 4 to 9
# [start, stop)
y = np.arange(4,10)
print(y)
# rank 1 ndarray that has evenly spaced integers from 1 to 13 in steps of 3.
# np.arange(start,stop,step)
z = np.arange(1,14,3)
print(z)

[0 1 2 3 4 5 6 7 8 9]
[4 5 6 7 8 9]
[ 1  4  7 10 13]


In [15]:
a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [16]:
#Slicing -- a[row:row, column:column]
#To get all rows and columns from 5 across and 5 down:
a[1:,1:]

array([[ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19],
       [21, 22, 23]])

In [17]:
#Try to get [14,15], [18,19]
print(f'{a[3:5, 2:]} \n')
#You can also change this elements using assignment and slicing 
#Try to get [9,10], [17,18] --- Here the [::,::] is [row:row:step, column:column:step]
a[2::2,1:3:] = [[90,100],[170,180]]
print(a)

[[14 15]
 [18 19]] 

[[  0   1   2   3]
 [  4   5   6   7]
 [  8  90 100  11]
 [ 12  13  14  15]
 [ 16 170 180  19]
 [ 20  21  22  23]]


In [18]:
np.mean(a), np.median(a)

(31.75, 13.5)

In [19]:
# 3 x 4 ndarray full of zeros
# np.zeros(shape)
X = np.zeros((3,4))
X

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
# a 3 x 2 ndarray full of ones
# np.ones(shape)
X = np.ones((3,2))
X

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [21]:
# 2 x 3 ndarray full of fives
# np.full(shape, constant value)
X = np.full((2,3), 5)
X

array([[5, 5, 5],
       [5, 5, 5]])

In [22]:
# Identity Matrix
# Since all Identity Matrices are square, the np.eye() function only takes a single integer as an argument
# 5 x 5 Identity matrix
X = np.eye(5)
X

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
# Diagonal Matrix
# 4 x 4 diagonal matrix that contains the numbers 10,20,30, and 50 on its main diagonal
X = np.diag([10,20,30,50])
X

array([[10,  0,  0,  0],
       [ 0, 20,  0,  0],
       [ 0,  0, 30,  0],
       [ 0,  0,  0, 50]])

In [24]:
np.random.random([3,3])

array([[0.37757748, 0.15041565, 0.17674133],
       [0.82593792, 0.8060459 , 0.75891128],
       [0.73783378, 0.09631616, 0.96206618]])

In [25]:
np.random.randint(0,100, size=(4,4))

array([[50, 67, 17, 82],
       [13, 53, 62, 43],
       [52, 92, 86,  0],
       [15, 48, 28, 21]])

In [26]:
np.linspace(1,20,40,retstep=True) #- equally spaced retstep gives the equidistance measure

(array([ 1.        ,  1.48717949,  1.97435897,  2.46153846,  2.94871795,
         3.43589744,  3.92307692,  4.41025641,  4.8974359 ,  5.38461538,
         5.87179487,  6.35897436,  6.84615385,  7.33333333,  7.82051282,
         8.30769231,  8.79487179,  9.28205128,  9.76923077, 10.25641026,
        10.74358974, 11.23076923, 11.71794872, 12.20512821, 12.69230769,
        13.17948718, 13.66666667, 14.15384615, 14.64102564, 15.12820513,
        15.61538462, 16.1025641 , 16.58974359, 17.07692308, 17.56410256,
        18.05128205, 18.53846154, 19.02564103, 19.51282051, 20.        ]),
 0.48717948717948717)

In [27]:
# Numpy random generation with a seed 
np.random.RandomState(43).randint(1,100,64).reshape(8,8) #rantint (start, stop, number of random ints)

array([[69, 65, 50, 22, 59, 17, 52, 18],
       [60, 92, 67, 31, 88, 65, 36, 51],
       [76, 90, 66, 35, 76, 67,  5, 37],
       [77, 89, 48, 33, 75, 61, 74, 35],
       [49, 53, 69, 29, 74,  8, 62, 85],
       [48, 54, 33,  4, 35, 42, 26, 30],
       [27, 54, 86, 22, 75, 28, 59,  8],
       [96, 62, 52, 35, 47, 53, 19, 24]])

In [28]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])

a + b

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [29]:
a - b

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [30]:
a * b ##Not matrix multiplication -- for this we use dot product 

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [31]:
a.dot(b)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [32]:
np.dot(a,b)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])